name: Update README

on:
  schedule:
    # Runs at 12am UTC every day
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: gopal-jogi
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Updated Snake Animation" || echo "No changes to commit"
          git push
